// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV3wi_be-TaXLxVku2Oi7VpeQNYgm3hQI',
    appId: '1:63331672690:web:43e627032ec47c5c58d8eb',
    messagingSenderId: '63331672690',
    projectId: 'thimar-bb73a',
    authDomain: 'thimar-bb73a.firebaseapp.com',
    storageBucket: 'thimar-bb73a.firebasestorage.app',
    measurementId: 'G-E9M65XCVNW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3u13j0sJWCboFcyyvtvD7iBLZlOQW9cw',
    appId: '1:63331672690:android:afc4dfaf7239c50458d8eb',
    messagingSenderId: '63331672690',
    projectId: 'thimar-bb73a',
    storageBucket: 'thimar-bb73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-Nc1bTU5MlzxxmfKaZv9mafApOIf-5E',
    appId: '1:63331672690:ios:00f5bd3fa28202a058d8eb',
    messagingSenderId: '63331672690',
    projectId: 'thimar-bb73a',
    storageBucket: 'thimar-bb73a.firebasestorage.app',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-Nc1bTU5MlzxxmfKaZv9mafApOIf-5E',
    appId: '1:63331672690:ios:00f5bd3fa28202a058d8eb',
    messagingSenderId: '63331672690',
    projectId: 'thimar-bb73a',
    storageBucket: 'thimar-bb73a.firebasestorage.app',
    iosBundleId: 'com.example.thimar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCV3wi_be-TaXLxVku2Oi7VpeQNYgm3hQI',
    appId: '1:63331672690:web:a39e6697ec2c1bc258d8eb',
    messagingSenderId: '63331672690',
    projectId: 'thimar-bb73a',
    authDomain: 'thimar-bb73a.firebaseapp.com',
    storageBucket: 'thimar-bb73a.firebasestorage.app',
    measurementId: 'G-010N8Q03LB',
  );
}
